[versions]
agp = "8.6.1"
kotlin = "1.9.22"
coreKtx = "1.13.1"
appcompat = "1.7.0"
kotlinxCoroutinesCore = "1.9.0"
ktorClientAndroid = "2.3.11"
ktorClientContentNegotiation = "2.3.11"
ktorClientCore = "2.3.11"
material = "1.12.0"
vanniktech="0.28.0"
nmcp="0.0.8"
dagger="2.52"
lifecycleProcess="2.8.6"
uiAndroid = "1.7.4"
compose = "1.7.4"

junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
activity-compose = "1.9.3"
mockitoCore="5.5.0"
mockitoKt="4.0.0"
archTest="2.2.0"
coroutinesTest="1.9.0"
robolectricVersion="4.12.2"
[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKt" }
robolectric = {group = "org.robolectric", name = "robolectric",  version.ref ="robolectricVersion"}
mockito-android = { group = "org.mockito", name = "mockito-android", version.ref = "mockitoCore" }
androidx-arch-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "archTest" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesTest" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorClientAndroid" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktorClientCore" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientContentNegotiation" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktorClientAndroid" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorClientAndroid" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
dagger = { group="com.google.dagger", name= "dagger", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }
androidx-ui-android = { group = "androidx.compose.ui", name = "ui-android", version.ref = "uiAndroid" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id="kotlin-kapt"}
vanniktech-deployer = { id="com.vanniktech.maven.publish", version.ref = "vanniktech"}
gradleup-nmcp= {id="com.gradleup.nmcp", version.ref="nmcp"}
