signing.keyId=3E104946
signing.password=m3ak00830
#signing.keyId=4A12535D
#signing.password=besoIntemptSDK
#signing.secretKeyRingFile="C:/Users/gugus/Desktop/secring.gpg"

#ossrhUsername=intempt
#ossrhPassword=Intempt$1234

ossrhUsername=O/fBkqaR
ossrhPassword=NMDXe0mX0Ea6labudGXY1ayWd7gnX3tC1SowXaNEcp5N


#ossrhUsername=LTY6xIZj
#ossrhPassword=/FeU+q0Hnjx7e3bzwQaI5uD9T43hH4xifrASqJBmAz+o


